CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    fullName VARCHAR(100) NOT NULL,
    mobile VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(150) UNIQUE NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    createAt TIMESTAMP DEFAULT NOW(),
    updatedAt TIMESTAMP
);
